import type { PrimitiveDescriptor } from './types.js';

export const PRIMITIVES: PrimitiveDescriptor[] = [
  {
    id: 'reveal.precision-rise',
    kind: 'reveal',
    summary: 'Restrained opacity + short upward settle for high-frequency product/UI entrances.',
    capabilities: ['choreography', 'ui-motion'],
    videoTypes: ['product-launch', 'ui-demo', 'brand-film', 'presentation'],
    styles: ['premium-minimal', 'tech-minimal', 'cinematic-product'],
    energies: ['restrained', 'controlled'],
    dimensionality: ['2d', '2.5d'],
    tags: ['entrance', 'fade', 'translate', 'restrained'],
    sources: [
      { donor: 'onda', path: 'lib/choreography.ts', note: 'Closed motion vocabulary and restrained entry patterns.' },
      { donor: 'motion-design-skill', path: 'SKILL.md', note: 'Purposeful choreography and hierarchy.' },
    ],
    antiPatterns: ['large arbitrary travel', 'bouncy entrance'],
  },
  {
    id: 'reveal.hero-settle',
    kind: 'reveal',
    summary: 'Two-stage hero landing with controlled scale/depth emphasis and a deliberate hold.',
    capabilities: ['choreography', 'shot-design'],
    videoTypes: ['product-launch', 'brand-film', 'cinematic-3d', 'logo-identity'],
    styles: ['premium-minimal', 'cinematic-product'],
    energies: ['controlled', 'dynamic'],
    dimensionality: ['2d', '2.5d', '3d'],
    tags: ['hero', 'landing', 'settle', 'focal-point'],
    sources: [
      { donor: 'onda', path: 'lib/choreography.ts', note: 'Hero landing concept.' },
      { donor: 'video-shotcraft', path: 'SKILL.md', note: 'Single-hero action arcs and breathing room.' },
    ],
    antiPatterns: ['repeating hero treatment on every element', 'overshoot as decoration'],
  },
  {
    id: 'exit.clean-fall',
    kind: 'exit',
    summary: 'Fast, low-travel exit that clears the frame without competing with the next focal point.',
    capabilities: ['choreography', 'transitions'],
    videoTypes: ['product-launch', 'ui-demo', 'brand-film', 'presentation'],
    styles: ['premium-minimal', 'tech-minimal', 'editorial'],
    energies: ['restrained', 'controlled', 'dynamic'],
    dimensionality: ['2d', '2.5d'],
    tags: ['exit', 'fade', 'continuity'],
    sources: [{ donor: 'onda', path: 'lib/choreography.ts', note: 'Exits should generally be faster than entrances.' }],
  },
  {
    id: 'typography.word-stagger',
    kind: 'typography',
    summary: 'Word-level stagger with a bounded cadence and legibility-first hold.',
    capabilities: ['kinetic-typography', 'choreography'],
    videoTypes: ['kinetic-type', 'brand-film', 'product-launch', 'social'],
    styles: ['editorial', 'expressive', 'premium-minimal'],
    energies: ['controlled', 'dynamic', 'aggressive'],
    dimensionality: ['2d'],
    tags: ['type', 'words', 'stagger', 'headline'],
    sources: [
      { donor: 'motion-skills', path: 'SKILL.md', note: 'Kinetic typography routing.' },
      { donor: 'onda', path: 'lib/motion.ts', note: 'Consistent sibling stagger principle.' },
    ],
    antiPatterns: ['random per-word timing', 'unreadable overlap'],
  },
  {
    id: 'typography.line-reveal',
    kind: 'typography',
    summary: 'Mask/clip-based line reveal for editorial headlines and chapter changes.',
    capabilities: ['kinetic-typography', 'transitions'],
    videoTypes: ['kinetic-type', 'brand-film', 'presentation', 'social'],
    styles: ['editorial', 'premium-minimal', 'expressive'],
    energies: ['restrained', 'controlled', 'dynamic'],
    dimensionality: ['2d'],
    tags: ['type', 'mask', 'headline', 'editorial'],
    sources: [
      { donor: 'motion-design-skill', path: 'SKILL.md' },
      { donor: 'remotion-scenes', path: 'src', note: 'Scene-level type and mask implementation corpus.' },
    ],
  },
  {
    id: 'typography.metric-counter',
    kind: 'typography',
    summary: 'Decisive numeric change with restrained emphasis for proof points and KPIs.',
    capabilities: ['kinetic-typography', 'data-animation'],
    videoTypes: ['data-story', 'product-launch', 'ui-demo', 'presentation'],
    styles: ['tech-minimal', 'premium-minimal', 'editorial'],
    energies: ['restrained', 'controlled', 'dynamic'],
    dimensionality: ['2d'],
    tags: ['number', 'counter', 'metric', 'proof'],
    sources: [
      { donor: 'chuk-motion', path: 'src', note: 'Design-system driven data motion.' },
      { donor: 'remotion-templates', path: '.', note: 'Reusable Remotion component corpus.' },
    ],
  },
  {
    id: 'ui.cursor-focus',
    kind: 'ui',
    summary: 'Geometry-aware pointer travel with visual focus transfer and click emphasis.',
    capabilities: ['ui-motion', 'choreography'],
    videoTypes: ['ui-demo', 'product-launch', 'explainer'],
    styles: ['tech-minimal', 'premium-minimal', 'cinematic-product'],
    energies: ['restrained', 'controlled', 'dynamic'],
    dimensionality: ['2d', '2.5d'],
    tags: ['cursor', 'product-demo', 'interaction', 'focus'],
    sources: [{ donor: 'remotion-cinematic', path: 'src', note: 'Geometry-aware cursor and product-demo choreography.' }],
    antiPatterns: ['cursor moving without explanatory purpose', 'teleporting cursor'],
  },
  {
    id: 'ui.viewport-push',
    kind: 'ui',
    summary: 'Scene-relative viewport/camera push toward a meaningful product state.',
    capabilities: ['ui-motion', 'cinematography'],
    videoTypes: ['ui-demo', 'product-launch'],
    styles: ['cinematic-product', 'premium-minimal', 'tech-minimal'],
    energies: ['controlled', 'dynamic'],
    dimensionality: ['2.5d'],
    tags: ['ui', 'zoom', 'camera', 'focus'],
    sources: [
      { donor: 'remotion-cinematic', path: 'src', note: 'Scene-relative camera architecture.' },
      { donor: 'video-shotcraft', path: 'SKILL.md', note: 'Real product capture + 2.5D camera language.' },
    ],
  },
  {
    id: 'ui.layered-product-frame',
    kind: 'ui',
    summary: 'Product UI surface separated into controlled depth planes for premium spatial presentation.',
    capabilities: ['ui-motion', 'cinematography'],
    videoTypes: ['ui-demo', 'product-launch', 'brand-film'],
    styles: ['cinematic-product', 'premium-minimal'],
    energies: ['restrained', 'controlled'],
    dimensionality: ['2.5d', '3d'],
    tags: ['ui', 'depth', 'layers', 'browser', 'device'],
    sources: [
      { donor: 'video-shotcraft', path: 'SKILL.md', note: 'Real screenshots, element extraction, depth treatment.' },
      { donor: 'theatre', path: 'packages', note: 'Spatial/keyframed motion reference.' },
    ],
  },
  {
    id: 'camera.parallax-2_5d',
    kind: 'camera',
    summary: 'Multi-plane parallax with bounded perspective for dimensional product/UI shots.',
    capabilities: ['cinematography', 'shot-design'],
    videoTypes: ['product-launch', 'ui-demo', 'brand-film', 'cinematic-3d'],
    styles: ['cinematic-product', 'premium-minimal'],
    energies: ['restrained', 'controlled', 'dynamic'],
    dimensionality: ['2.5d'],
    tags: ['camera', 'parallax', 'depth', '2.5d'],
    sources: [
      { donor: 'video-shotcraft', path: 'references/shots', note: 'Shot-card vocabulary.' },
      { donor: 'motion-canvas-examples', path: 'src', note: 'Parallax and camera math examples.' },
    ],
  },
  {
    id: 'camera.product-orbit',
    kind: 'camera',
    summary: 'Controlled orbit around a single hero object, reserving spatial drama for a focal moment.',
    capabilities: ['cinematography', 'three-d', 'shot-design'],
    videoTypes: ['product-launch', 'cinematic-3d', 'brand-film'],
    styles: ['cinematic-product', 'premium-minimal'],
    energies: ['controlled', 'dynamic'],
    dimensionality: ['3d'],
    tags: ['camera', 'orbit', 'hero', '3d', 'product'],
    sources: [
      { donor: 'video-shotcraft', path: 'SKILL.md', note: 'Orbit close-up as a premium shot grammar.' },
      { donor: 'theatre', path: 'packages', note: '3D sequencing and keyframing.' },
    ],
    antiPatterns: ['continuous orbit through whole film', 'orbit without focal subject'],
  },
  {
    id: 'camera.macro-push',
    kind: 'camera',
    summary: 'Slow push toward a detail, synchronized with content reveal rather than arbitrary zoom.',
    capabilities: ['cinematography', 'shot-design'],
    videoTypes: ['product-launch', 'brand-film', 'ui-demo'],
    styles: ['cinematic-product', 'premium-minimal', 'editorial'],
    energies: ['restrained', 'controlled'],
    dimensionality: ['2.5d', '3d'],
    tags: ['camera', 'macro', 'push', 'detail'],
    sources: [{ donor: 'video-shotcraft', path: 'references/shots', note: 'Cinematic shot recipe corpus.' }],
  },
  {
    id: 'transition.depth-cut',
    kind: 'transition',
    summary: 'Cut hidden by coordinated depth/camera movement so scene continuity feels spatial rather than decorative.',
    capabilities: ['transitions', 'cinematography'],
    videoTypes: ['product-launch', 'ui-demo', 'brand-film', 'cinematic-3d'],
    styles: ['cinematic-product', 'premium-minimal'],
    energies: ['controlled', 'dynamic'],
    dimensionality: ['2.5d', '3d'],
    tags: ['transition', 'camera', 'depth', 'continuity'],
    sources: [
      { donor: 'video-shotcraft', path: 'references/shots' },
      { donor: 'onda', path: 'lib', note: 'Systematic transition vocabulary.' },
    ],
  },
  {
    id: 'transition.mask-bridge',
    kind: 'transition',
    summary: 'Foreground or graphic mask carries visual momentum between two related scenes.',
    capabilities: ['transitions', 'shot-design'],
    videoTypes: ['product-launch', 'brand-film', 'kinetic-type', 'social'],
    styles: ['editorial', 'cinematic-product', 'expressive'],
    energies: ['controlled', 'dynamic', 'aggressive'],
    dimensionality: ['2d', '2.5d'],
    tags: ['transition', 'mask', 'wipe', 'bridge'],
    sources: [
      { donor: 'onda', path: 'lib' },
      { donor: 'remotion-scenes', path: 'src' },
    ],
  },
  {
    id: 'transition.match-move',
    kind: 'transition',
    summary: 'Match outgoing and incoming motion vectors so a hard cut preserves perceived momentum.',
    capabilities: ['transitions', 'choreography', 'shot-design'],
    videoTypes: ['brand-film', 'product-launch', 'kinetic-type', 'social'],
    styles: ['editorial', 'expressive', 'cinematic-product'],
    energies: ['dynamic', 'aggressive'],
    dimensionality: ['2d', '2.5d'],
    tags: ['transition', 'match-cut', 'momentum'],
    sources: [{ donor: 'motion-design-skill', path: 'SKILL.md', note: 'Choreography and continuity principles.' }],
  },
  {
    id: 'data.chart-build',
    kind: 'data',
    summary: 'Progressive chart construction that reveals data in narrative order instead of animating every mark simultaneously.',
    capabilities: ['data-animation', 'choreography'],
    videoTypes: ['data-story', 'explainer', 'presentation'],
    styles: ['tech-minimal', 'editorial', 'premium-minimal'],
    energies: ['restrained', 'controlled', 'dynamic'],
    dimensionality: ['2d'],
    tags: ['chart', 'data', 'graph', 'explain'],
    sources: [
      { donor: 'chuk-motion', path: 'src' },
      { donor: 'motion-canvas-examples', path: 'src' },
      { donor: 'remotion-skills', path: 'skills', note: 'Remotion implementation guidance.' },
    ],
  },
  {
    id: 'data.metric-proof',
    kind: 'data',
    summary: 'One strong metric plus contextual annotation, designed as a proof beat rather than dashboard decoration.',
    capabilities: ['data-animation', 'kinetic-typography'],
    videoTypes: ['product-launch', 'data-story', 'presentation', 'explainer'],
    styles: ['premium-minimal', 'tech-minimal', 'editorial'],
    energies: ['restrained', 'controlled'],
    dimensionality: ['2d'],
    tags: ['metric', 'proof', 'kpi', 'number'],
    sources: [{ donor: 'chuk-motion', path: 'src', note: 'Tokenized data-motion system.' }],
  },
  {
    id: 'effect.light-sweep',
    kind: 'effect',
    summary: 'Single restrained specular sweep used to articulate form or a premium surface once.',
    capabilities: ['choreography', 'shot-design'],
    videoTypes: ['product-launch', 'brand-film', 'logo-identity'],
    styles: ['premium-minimal', 'cinematic-product'],
    energies: ['restrained', 'controlled'],
    dimensionality: ['2d', '2.5d', '3d'],
    tags: ['light', 'specular', 'premium', 'accent'],
    sources: [{ donor: 'video-shotcraft', path: 'SKILL.md', note: 'Single high-quality light accent over repeated glow.' }],
    antiPatterns: ['constant glint', 'glow on every element'],
  },
  {
    id: 'effect.particle-accent',
    kind: 'effect',
    summary: 'Sparse particles reserved for a semantic event, impact, reveal, or atmospheric depth cue.',
    capabilities: ['webgl', 'choreography'],
    videoTypes: ['brand-film', 'cinematic-3d', 'experimental', 'social'],
    styles: ['cinematic-product', 'expressive', 'experimental'],
    energies: ['controlled', 'dynamic', 'aggressive'],
    dimensionality: ['2d', '3d', 'webgl'],
    tags: ['particles', 'accent', 'webgl'],
    sources: [
      { donor: 'motion-skills', path: 'SKILL.md' },
      { donor: 'motion-canvas-examples', path: 'src' },
    ],
    antiPatterns: ['meaningless ambient particles', 'particles on every scene'],
  },
  {
    id: 'webgl.shader-field',
    kind: 'webgl',
    summary: 'Generative shader surface used as a controlled material/background system, not generic futuristic decoration.',
    capabilities: ['webgl', 'three-d'],
    videoTypes: ['experimental', 'brand-film', 'cinematic-3d'],
    styles: ['experimental', 'cinematic-product'],
    energies: ['restrained', 'controlled', 'dynamic'],
    dimensionality: ['webgl'],
    tags: ['shader', 'glsl', 'generative', 'material'],
    sources: [
      { donor: 'motion-canvas-examples', path: 'src', note: 'GLSL example corpus.' },
      { donor: 'motion-skills', path: 'SKILL.md', note: 'WebGL/generative motion knowledge.' },
    ],
  },
  {
    id: 'audio.impact-stack',
    kind: 'audio',
    summary: 'Riser → impact → short detail accent mapped to one important visual event.',
    capabilities: ['sound-design', 'choreography'],
    videoTypes: ['product-launch', 'brand-film', 'cinematic-3d', 'social'],
    styles: ['cinematic-product', 'premium-minimal', 'expressive'],
    energies: ['controlled', 'dynamic', 'aggressive'],
    dimensionality: ['2d', '2.5d', '3d', 'webgl'],
    tags: ['audio', 'sfx', 'impact', 'riser'],
    sources: [{ donor: 'video-shotcraft', path: 'SKILL.md', note: 'Riser-impact-sparkle sound sentence.' }],
  },
  {
    id: 'audio.beat-map',
    kind: 'audio',
    summary: 'Music beat grid used to place major edits and accents while retaining breathing room between them.',
    capabilities: ['sound-design', 'choreography'],
    videoTypes: ['product-launch', 'brand-film', 'social', 'kinetic-type'],
    styles: ['cinematic-product', 'editorial', 'expressive'],
    energies: ['controlled', 'dynamic', 'aggressive'],
    dimensionality: ['2d', '2.5d', '3d', 'webgl'],
    tags: ['audio', 'music', 'beat', 'sync', 'edit'],
    sources: [{ donor: 'video-shotcraft', path: 'references/music-beat-sync.md' }],
  },
  {
    id: 'scene.hero-product',
    kind: 'scene',
    summary: 'Hero composition combining one focal subject, controlled camera/depth, minimal copy, and a deliberate settle.',
    capabilities: ['creative-direction', 'shot-design', 'cinematography', 'choreography'],
    videoTypes: ['product-launch', 'brand-film', 'cinematic-3d'],
    styles: ['premium-minimal', 'cinematic-product'],
    energies: ['restrained', 'controlled', 'dynamic'],
    dimensionality: ['2.5d', '3d'],
    tags: ['scene', 'hero', 'product', 'launch'],
    sources: [
      { donor: 'video-shotcraft', path: 'SKILL.md' },
      { donor: 'product-launch-video-skill', path: 'SKILL.md' },
      { donor: 'motion-design-skill', path: 'SKILL.md' },
    ],
  },
  {
    id: 'scene.ui-feature',
    kind: 'scene',
    summary: 'Feature explanation scene using real UI, one interaction goal, camera focus, and a readable post-action hold.',
    capabilities: ['ui-motion', 'shot-design', 'choreography'],
    videoTypes: ['ui-demo', 'product-launch', 'explainer'],
    styles: ['tech-minimal', 'premium-minimal', 'cinematic-product'],
    energies: ['restrained', 'controlled', 'dynamic'],
    dimensionality: ['2d', '2.5d'],
    tags: ['scene', 'ui', 'feature', 'product-demo'],
    sources: [
      { donor: 'remotion-cinematic', path: 'src' },
      { donor: 'video-shotcraft', path: 'SKILL.md' },
    ],
  },
  {
    id: 'scene.editorial-statement',
    kind: 'scene',
    summary: 'Typographic scene built around one statement, a strong scale relationship, and one dominant motion idea.',
    capabilities: ['creative-direction', 'kinetic-typography', 'choreography'],
    videoTypes: ['kinetic-type', 'brand-film', 'social', 'presentation'],
    styles: ['editorial', 'expressive', 'premium-minimal'],
    energies: ['controlled', 'dynamic', 'aggressive'],
    dimensionality: ['2d'],
    tags: ['scene', 'type', 'editorial', 'statement'],
    sources: [
      { donor: 'motion-design-skill', path: 'SKILL.md' },
      { donor: 'motion-skills', path: 'SKILL.md' },
    ],
  },
];

export const PRIMITIVE_BY_ID = new Map(PRIMITIVES.map((primitive) => [primitive.id, primitive]));
